import { Billing } from './Billing';
import { Shipping } from './Shipping';
import { OrderLineItem } from './OrderLineItem';
import { OrderTaxLine } from './OrderTaxLine';
import { OrderShippingLine } from './OrderShippingLine';
import { OrderFeeLine } from './OrderFeeLine';
import { OrderCouponLine } from './OrderCouponLine';
import { OrderRefund } from './OrderRefund';
import { MetaData } from './MetaData';

export interface Order {
  id?: number;
  parent_id?: number;
  number?: string;
  order_key?: string;
  created_via?: string;
  version?: string;
  status?: 'pending' | 'processing' | 'on-hold' | 'completed' | 'cancelled' | 'refunded' | 'failed';
  currency?: string;
  date_created?: string;
  date_created_gmt?: string;
  date_modified?: string;
  date_modified_gmt?: string;
  discount_total?: string;
  discount_tax?: string;
  shipping_total?: string;
  shipping_tax?: string;
  cart_tax?: string;
  total?: string;
  total_tax?: string;
  prices_include_tax?: boolean;
  customer_id?: number;
  customer_ip_address?: string;
  customer_user_agent?: string;
  customer_note?: string;
  billing?: Billing;
  shipping?: Shipping;
  payment_method?: string;
  payment_method_title?: string;
  transaction_id?: string;
  date_paid?: string;
  date_paid_gmt?: string;
  date_completed?: string;
  date_completed_gmt?: string;
  cart_hash?: string;
  meta_data?: MetaData[];
  line_items?: OrderLineItem[];
  tax_lines?: OrderTaxLine[];
  shipping_lines?: OrderShippingLine[];
  fee_lines?: OrderFeeLine[];
  coupon_lines?: OrderCouponLine[];
  refunds?: OrderRefund[];
  set_paid?: boolean;
} 